// <auto-generated />
namespace QuanLyRenLuyen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createda));
        
        string IMigrationMetadata.Id
        {
            get { return "202203110740223_createda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
